fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "v6.0.0"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "v7.1.0"
  symlinks:
    aptly: "#{source_dir}"
